// Generated by ReScript, PLEASE EDIT WITH CARE


function length(head) {
  if (head) {
    return 1 + length(head._1) | 0;
  } else {
    return 0;
  }
}

var head = /* Node */{
  _0: 1,
  _1: /* Node */{
    _0: 2,
    _1: /* Node */{
      _0: 3,
      _1: /* Empty */0
    }
  }
};

console.log(length(head));

export {
  length ,
  head ,
}
/*  Not a pure module */
