// Generated by ReScript, PLEASE EDIT WITH CARE


var initialState = {
  counter: 0,
  userName: "John Doe"
};

function getState(param) {
  return initialState;
}

function incrementCounter(currentState) {
  return {
          counter: currentState.counter + 1 | 0,
          userName: currentState.userName
        };
}

function decrementCounter(currentState) {
  return {
          counter: currentState.counter - 1 | 0,
          userName: currentState.userName
        };
}

function setUserName(currentState, newName) {
  return {
          counter: currentState.counter,
          userName: newName
        };
}

var StateModule = {
  initialState: initialState,
  getState: getState,
  incrementCounter: incrementCounter,
  decrementCounter: decrementCounter,
  setUserName: setUserName
};

export {
  StateModule ,
}
/* No side effect */
