// Generated by ReScript, PLEASE EDIT WITH CARE


function height(root) {
  if (typeof root === "number" || root.TAG === /* Leaf */0) {
    return 0;
  } else {
    return 1 + Math.max(height(root._1), height(root._2)) | 0;
  }
}

var root = {
  TAG: /* Node */1,
  _0: 1,
  _1: {
    TAG: /* Node */1,
    _0: 2,
    _1: {
      TAG: /* Leaf */0,
      _0: 1
    },
    _2: /* Nil */0
  },
  _2: {
    TAG: /* Leaf */0,
    _0: 3
  }
};

console.log(height(root));

export {
  height ,
  root ,
}
/*  Not a pure module */
